### PR TITLE
Set the outer ObjectMeta when decoding a wrapper struct

### PR DESCRIPTION
**Pull request by palourde**
Signed-off-by: Simon Plourde <simon@sensu.io>

## What is this change?

It fixes a bug in the Wrapper's UnmarshalJSON method, which would cause wrapped resources to not properly display their metadata or prevent them from being created.

It also adds more comments and unit tests to the same UnmarshalJSON method.

## Why is this change necessary?

Fixes https://github.com/sensu/sensu-enterprise-go/issues/704
Fixes https://github.com/sensu/sensu-go/issues/3442
Fixes https://github.com/sensu/sensu-go/issues/3444

## Does your change need a Changelog entry?

Added!

## Do you need clarification on anything?

Nope.

## Were there any complications while making this change?

Nope.

## Have you reviewed and updated the documentation for this change? Is new documentation required?

Nope.

## How did you verify this change?

Manually tested that it fixed the reported bugs and added unit tests to cover these cases.

## Is this change a patch?

Yep, but we are not proceeding with a patch release for 5.15.

### CODE REVIEW

**Comment by palourde** [comment]
@ccressent Feel free to push commits to this branch if you add more/better tests!

**Comment by palourde** [comment]
@echlebek It works for both core and enterprise resources but wrapped resources won't populate the outer metadata. I suppose I could easily modify the encoding methods so we always have both the inner and outer metadata filled internally but only display the external one when decoding; right now [sensuctl does a hack](https://github.com/sensu/sensu-go/blob/0d76ff14412bb2d1b7e80662051943a605fe8dd0/cli/commands/helpers/yaml.go#L20:6) to accomplish that.

**Comment by palourde** [comment]
@echlebek @ccressent Alright, I think I finally figured out how to have a consistent behavior across our codebase with the wrapper.

Essentially, when we decode a `Wrapper`, we first fill the innerMeta with the help of the outerMeta, and then set the outerMeta with the value of innerMeta. By doing so, users can provide the outer and/or inner meta but internally we fill both:
https://github.com/sensu/sensu-go/blob/ba9c8287cc4ad0a214d12589fd08ef7ce3e6865b/types/wrapper.go#L147-L171

Then, I moved the encoding logic from sensuctl to the `MarshalJSON` & `MarshalYAML` methods; This logic is required so the innerMeta is discarded and the YAML format also omits empty fields. From this point, sensuctl and the API will display wrapped resources the same way:
https://github.com/sensu/sensu-go/blob/ba9c8287cc4ad0a214d12589fd08ef7ce3e6865b/types/wrapper.go#L59-L109

**Comment by echlebek** [comment]
I hope this works :joy:

**Comment by ccressent** [comment]
The funny thing is that your outer --> inner --> outer thing is what I arrived at while trying to fix this issue and what I showed Eric before we decided it might be dealt with as a pure display issue! So I suppose it's comforting to know we both independently arrived at the same conclusion :)

**Pull request merged**
