### PR TITLE
Test metric extraction with an integration test

### LINKED ISSUE #1597: Test metric extraction with an integration test
Test that metric extraction is working with an integration test. The test should work similarly to the e2e test, and validate that check output is being transferred to metrics events as appropriate.

### PR DESCRIPTION
**Pull request by nikkiki**
Signed-off-by: Nikki Attea <nikki@sensu.io>

## What is this change?

Removes check output metric extraction e2e test, in favor of more detailed integration coverage.

## Why is this change necessary?

Closes #1597 

## Does your change need a Changelog entry?

Yas.

## Do you need clarification on anything?

Nah.

## Were there any complications while making this change?

Yas.

### CODE REVIEW

**Comment by cyphus** [comment]
Would it be possible to simplify this further by changing the command from `cat` to `echo`, thereby avoiding creating the temporary file?

I'm always a fan of net code loss 😎

**Comment by nikkiki** [comment]
@cyphus We could, if we wrote a go program `echo` in [sensu-go/tools](https://github.com/sensu/sensu-go/tree/882d062bf337350a5344e94e6e9fd2a4bf313e0b/tools). These "commands" are actually executables that mimic the original shell commands. The program itself would be fairly simple, but arguably a small code gain 😆. It's not a bad idea though, especially for future tests!

**Comment by nikkiki** [comment]
I think we actually could write to stdin to avoid the temp file, without having to write an `echo` command.

**Comment by nikkiki** [comment]
_Remembers why the temp file was easier.._

**Comment by nikkiki** [comment]
giphy-1

**Pull request merged**
