### PR TITLE
Add sensuctl cluster member-add command.

### LINKED ISSUE #1719: Add sensuctl cluster member add command
Add a command to sensuctl that will allow an administrator to add a member to a sensu cluster.

The command should be backed by support in apid. See https://godoc.org/github.com/coreos/etcd/clientv3#Cluster for more information on how to add members to an etcd cluster with etcd clientv3.

### PR DESCRIPTION
**Pull request by echlebek**
Signed-off-by: Eric Chlebek <eric@sensu.io>

## What is this change?

Closes #1719

### CODE REVIEW

**Comment by echlebek** [comment]
@palourde, cluster operators need a way to modify existing clusters, and that is the intent of the commands we are adding. For instance, you start with a 3 node cluster, and one node becomes unstable, so you remove it from the cluster, and add another.

The difference is the initial cluster state: existing vs new.

See the docs here: https://coreos.com/etcd/docs/latest/etcd-live-cluster-reconfiguration.html

**Comment by echlebek** [comment]
I've amended the commit with a (hopefully) more clear description for the command.

**Comment by oferrigni** [comment]
LGTM

**Comment by echlebek** [comment]
Thanks for the prompt reviews everyone!

**Pull request merged**
