### PR TITLE
Make entity_class optional in /events API

### PR DESCRIPTION
**Pull request by nikkixdev**
Signed-off-by: Nikki Attea <nikki@sensu.io>

## What is this change?

Default `event.entity.entity_class` to `proxy` in the POST/PUT `/events` API.

## Why is this change necessary?

Closes https://github.com/sensu/sensu-go/issues/3525

## Does your change need a Changelog entry?

Yas.

## Do you need clarification on anything?

Nah.

## Were there any complications while making this change?

Nah.

## Have you reviewed and updated the documentation for this change? Is new documentation required?

We good.

## How did you verify this change?

Unit test added. Tested the payload in the original issue.

## Is this change a patch?

Milestone is 5.18.0 so merging this into master.

### CODE REVIEW

**Comment by echlebek** [comment]
Perhaps we should disable client-side validation in sensuctl, leaving it up to the backend alone.

**Comment by nikkixdev** [comment]
@echlebek good call.. let me see if that is possible without a large amount of refactoring..

**Comment by nikkixdev** [comment]
@echlebek so I've done some local testing and debugging, and the backend already attempts to validate the resource at the store level. Those errors are properly passed back up to the HTTP API. Therefore, `sensuctl create`'s validation call is redundant.. wdyt of just removing that block completely?

https://github.com/sensu/sensu-go/blob/e762d55833e5ce67edd3161ce436bce0e9823db6/cli/commands/create/create.go#L253-L261

Validation errors are still surfaced:
```
Error: error putting resource 0 (/api/core/v2/namespaces/default/events/I-..%2F/helloworld): entity is invalid: entity name cannot contain spaces or special characters
```

**Comment by echlebek** [comment]
@nikkixdev I think it's fine to remove client-side validation, it should reduce friction between minor versions as well.

**Comment by calebhailey** [comment]
🙌 EXCITED 🙌

**Pull request merged**
