### PR TITLE
Update package dgrijalva/jwt-go to golang-jwt/jwt

### PR DESCRIPTION
**Pull request by sspaink**
Signed-off-by: Sebastian Spaink <sspaink@influxdata.com>

## What is this change?

The package https://github.com/dgrijalva/jwt-go has been archived and contains a CVE (https://github.com/advisories/GHSA-w73w-5m7g-f7qc), the project has migrated to https://github.com/golang-jwt/jwt. This pull request just replaces the dependency to use the new project following the migration guide: https://github.com/golang-jwt/jwt/blob/main/MIGRATION_GUIDE.md this should be backwards compatible.

## Why is this change necessary?

My motivation for this change is that the Telegraf project has a output plugin for [Sensu](https://github.com/influxdata/telegraf/tree/master/plugins/outputs/sensu) and uses sensu-go which is indirectly pulling in `dgrijalva/jwt-go`.

## Does your change need a Changelog entry?

Yes, changelog has been updated

## How did you verify this change?

Not sure to be honest, but I did run `./build.sh`

### CODE REVIEW

**Comment by sspaink** [comment]
@echlebek I'm not entirely sure why the linters are failing with `Can't run linter unused: buildir: failed to load package : could not load export data: no export data for \"github.com/golang-jwt/jwt/v4\""`, any idea why?

**Comment by echlebek** [comment]
@sspaink I'm not sure why either. It could be a network issue, or availability problem with the Go module proxy. I'll try re-running the workflow, and if it fails again will dig deeper.

**Comment by echlebek** [comment]
Looks like the core/v2 module needs to be updated, I can do that.

**Review by echlebek — APPROVED** [review]

**Comment by echlebek** [comment]
@sspaink many thanks for the PR. We'll be releasing new tags for the `api/core/v2` and `types` modules soon, so that you can make use of this downstream if you are relying only on the domain types.

We'll be releasing version 6.5 of sensu-go in the next few weeks, so if you were depending on the entire project, it will take a bit longer.

**Pull request merged**
