### PR TITLE
Record GOARM value at build time

### PR DESCRIPTION
**Pull request by amdprophet**
## What is this change?

Stores the GOARM value (if set) in the entity system info.

## Why is this change necessary?

The ability to filter on which ARM version an asset is built for is a necessary for installations with varying versions of ARM processors.

A prerequisite for https://github.com/sensu/sensu-go/issues/3067.

## Does your change need a Changelog entry?

Yes.

## How did you verify this change?

I built the backend, agent, & sensuctl and inspected an agent entity running on this code:

Screen Shot 2019-08-15 at 2 30 38 PM

### CODE REVIEW

**Comment by portertech** [comment]
Does it make any sense for a more generalized field? e.g. arch_version?

**Comment by amdprophet** [comment]
@portertech I think that makes sense. I'll make the change.

**Comment by echlebek** [comment]
@portertech IMO no, because there is no corresponding Go compiler flag for those arch versions. I believe the Go runtime uses feature detection for Intel/AMD, and I'm not aware of any other arch specific compiler flags for other non-x86.

**Comment by amdprophet** [comment]
@echlebek is there a potential for something similar to happen with other architectures down the road? e.g. mips, sparc, powerpc?

**Comment by echlebek** [comment]
I can't predict the future, and that's why I'd prefer to add a distinct field if and when that scenario arises. :)

**Comment by amdprophet** [comment]
`GOMIPS` exists but is used to control whether or not floats are soft/hard. I'll stick with `ARMVersion` for now.

**Comment by portertech** [comment]
@amdprophet @echlebek just feels strange to have arch: i386, arm_version: "".

**Comment by echlebek** [comment]
Oh, yeah. It should have `omitempty` specified so that it doesn't render for its zero value

**Comment by echlebek** [comment]
@portertech the generated code indicates that `omitempty` is set, so the situation you describe will never arise.

**Pull request merged**
