### PR TITLE
Add username as field in API request logger

### PR DESCRIPTION
**Pull request by nikkictl**
Signed-off-by: Nikki Attea <nikki@sensu.io>

## What is this change?

Adds the username as a field in the API request logger by extracting the jwt claims from the request context. PR required in sensu-enterprise-go to ensure the `SimpleLogger` is called _after_ authentication.

## Why is this change necessary?

Closes https://github.com/sensu/sensu-go/issues/3763

## Does your change need a Changelog entry?

Yas.

## Do you need clarification on anything?

Nah.

## Were there any complications while making this change?

Nah.

## Have you reviewed and updated the documentation for this change? Is new documentation required?

We good.

## How did you verify this change?

Checked the logs on requests using tokens and api keys.
```
{"component":"apid","duration":"1.272ms","level":"info","method":"GET","msg":"request completed","path":"/api/core/v2/namespaces/default/events","size":2832,"status":200,"time":"2020-05-18T12:10:14-07:00","user":"admin"}
```

## Is this change a patch?

Yas, targeting release/5.20 branch.

### CODE REVIEW

**Comment by palourde** [comment]
I do see a possible problem here: since we are moving the position of the SimpleLogger middleware, any requests that return an error before we have time execute this one will not be logged.

For example, on master, if I try to poke the API with an invalid API token, I will have the following entry:

```
{"component":"apid","duration":"0.082ms","level":"info","method":"GET","msg":"request completed","path":"/api/core/v2/events","size":38,"status":401,"time":"2020-05-19T15:04:16-04:00"}
```

On this branch, I no longer see it =/

**Comment by nikkictl** [comment]
Ah, I see how the order of operations can get tricky here. Well we need the auth middleware to run before we can log the username, otherwise we don't know what the username is from the context. Perhaps a new username logger middleware could be run instead of loading this logic in the existing logger. WDYT @palourde?

**Comment by nikkictl** [comment]
I wonder if there is a way to do this with the hijack logger.. I'll have to look into it more!

**Comment by nikkictl** [comment]
I moved the logger middleware right after the auth layer, and invoked the logger manually on auth errors.

Now, the user is logged when auth is successful:
```
{"component":"apid","duration":"2.593ms","level":"info","method":"GET","msg":"request completed","path":"/api/core/v2/events","size":5649,"status":200,"time":"2020-05-20T10:01:54-07:00","user":"admin"}
```

And a 401 is logged when auth is not successful:
```
{"component":"apid","error":"key /sensu.io/apikeys/68c2027c-f286-4dca-bf9d-c32a1294b2cdd not found","level":"warning","msg":"invalid api key","time":"2020-05-20T10:01:59-07:00"}
{"component":"apid","duration":"0.021ms","level":"info","method":"GET","msg":"request completed","path":"/api/core/v2/events","size":42,"status":401,"time":"2020-05-20T10:01:59-07:00","user":""}
```

**Pull request merged**
