### PR TITLE
[Web UI] Use cron value in check list

### LINKED ISSUE #1909: [Web UI] Description of check's scheduled using cron field is incorrect
## Expected Behavior

Properly reflect state.

## Current Behavior

Check's scheduled using cron field are said to be "executed every 0 seconds".

## Possible Solution

Use `<CronDescription />` component.
 
## Steps to Reproduce (for bugs)

1. Create check with `cron` field set.
2. View in check's list.

### PR DESCRIPTION
**Pull request by jamesdphillips**
## What is this change?

Reflect cron value in the check list.

screen shot 2018-08-01 at 4 32 10 pm

## Why is this change necessary?

Fixes #1909 

## Does your change need a Changelog entry?

Introduced after last release.

## Do you need clarification on anything?

`undefined`

## Were there any complications while making this change?

`undefined`

## Have you reviewed and updated the documentation for this change? Is new documentation required?

`undefined`

### CODE REVIEW

**Comment by palourde** [comment]
@jamesdphillips Somehow I can't reproduce this on my local machine. I'm running Chrome with disabled cache on this branch, and I get the following:

screen shot 2018-08-02 at 10 58 54 am

```
 $ sensuctl check info check-cron
=== check-cron
Name:            check-cron
Interval:        0
Command:         echo 0
Cron:            * * * * *
Timeout:         0
TTL:             0
Subscriptions:   linux
Handlers:
Runtime Assets:
Hooks:
Publish?:        true
Stdin?:          false
Proxy Entity ID:
Organization:    default
Environment:     default
Metric Format:
Metric Handlers:
```

**Comment by jamesdphillips** [comment]
@palourde isn't `every minute` correct given the cron statement? Prior to this change it would have simply stated `every 0s seconds`.

**Comment by palourde** [comment]
Ah I see, thanks

**Comment by jamesdphillips** [comment]
My PR description wasn't very clear, sorry about that.

**Pull request merged**
