### PR TITLE
Add CountEvents store method

### PR DESCRIPTION
**Pull request by echlebek**
## What is this change?

The CountEvents store method will be used by the Web UI to know how many
pages of results are available, when using pagination.

## Why is this change necessary?

Supporting work for ongoing maintenance related to #4487

## Does your change need a Changelog entry?

No

## How did you verify this change?

Integration testing.

## Is this change a patch?

No.

### CODE REVIEW

**Review by fguimond — APPROVED** [review]
LGTM

**Review by ccressent — COMMENTED** [review]
Can we leverage [this existing method](https://github.com/sensu/sensu-go/blob/58481edfabb48ca7bd2bf3840bc4a0cbbf7230eb/backend/store/etcd/store.go#L240-L258)?

**Comment by echlebek** [comment]
@ccressent unfortunately it causes an import cycle, but I can copypasta the implementation so that it's the same.

**Comment by echlebek** [comment]
@ccressent yes!

**Review by jamesdphillips — APPROVED** [review]

**Pull request merged**
