### PR TITLE
don't defer timer reset, fixes #3062

### LINKED ISSUE #3062: Proxy check requests are scheduled too infrequently
It appears that events for proxy check requests are not updated each interval. Rather, the splayed executions are not scheduled until _after_ the whole interval.

## Expected Behavior
60 second check interval, 2 proxy entities, 50% splay:
- 60s between proxy1 executions
- 60s between proxy2 executions
- 15s between proxy1 -> proxy2 execution

## Current Behavior
60 second check interval, 2 proxy entities, 50% splay:
- 90s between proxy1 executions
- 90s between proxy2 executions
- 15s between proxy1 -> proxy2 execution

## Possible Solution
Splayed executions should be scheduled immediately, not after the original interval.

## Steps to Reproduce (for bugs)
1. Create the following proxy entities
```
{
  "type": "Entity",
  "api_version": "core/v2",
  "metadata": {
    "name": "proxy1",
    "namespace": "default"
  },
  "spec": {
    "deregister": false,
    "deregistration": {},
    "entity_class": "proxy",
    "last_seen": 0,
    "subscriptions": null,
    "system": {
      "network": {
        "interfaces": null
      }
    }
  }
}
{
  "type": "Entity",
  "api_version": "core/v2",
  "metadata": {
    "name": "proxy2",
    "namespace": "default"
  },
  "spec": {
    "deregister": false,
    "deregistration": {},
    "entity_class": "proxy",
    "last_seen": 0,
    "subscriptions": null,
    "system": {
      "network": {
        "interfaces": null
      }
    }
  }
}
```
2. Create the following check
```
{
  "type": "CheckConfig",
  "api_version": "core/v2",
  "metadata": {
    "name": "check-proxy",
    "namespace": "default"
  },
  "spec": {
    "check_hooks": null,
    "command": "echo hi",
    "env_vars": null,
    "handlers": [],
    "high_flap_threshold": 0,
    "interval": 60,
    "low_flap_threshold": 0,
    "output_metric_format": "",
    "output_metric_handlers": null,
    "proxy_entity_name": "",
    "proxy_requests": {
      "entity_attributes": [
        "entity.entity_class == 'proxy'"
      ],
      "splay": true,
      "splay_coverage": 50
    },
    "publish": true,
    "round_robin": false,
    "runtime_assets": null,
    "stdin": false,
    "subdue": null,
    "subscriptions": [
      "proxy"
    ],
    "timeout": 0,
    "ttl": 0
  }
}
```
3. Start the backend
4. Start the agent (`--subscriptions proxy`)
5. Executions are 90 seconds apart: `sensuctl event info proxy1 check-proxy --format json | jq .check.history`
6. Executions are 90 seconds apart: `sensuctl event info proxy2 check-proxy --format json | jq .check.history`

## Context
With the check splay and proxy entity configurations, each check should execute every 60 seconds (and 15 seconds apart from each other: 60 second interval * 50% / 2 entities = 15 second splay). The current behavior is not at parity with 1.x or docs.

Reported by `AdamskiEM`/@adammcdonagh in the community slack.

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.9.0
* Installation method (packages, binaries, docker etc.): binaries
* Operating System and version (e.g. Ubuntu 14.04): MacOS

### PR DESCRIPTION
**Pull request by roganartu**
## What is this change?

Implementing fix to root cause I identified in #3062.

## Why is this change necessary?

Splayed proxy checks are executed too infrequently, as the timer wasn't being reset until after all the splayed checks had been scheduled.

## Does your change need a Changelog entry?

Yes, added one.

## Do you need clarification on anything?

No, I implemented this approach to fix after @echlebek indicated it should be safe so the more complex approach was unnecessary.

## Were there any complications while making this change?

No.

## Have you reviewed and updated the documentation for this change? Is new documentation required?

No documentation change necessary.

## How did you verify this change?

Unverified.

### CODE REVIEW

**Comment by echlebek** [comment]
Thanks for the PR!

I did some validation of this change with the reproduction resources that Nikki posted in the original issue. The tables below shows timestamps from the histories of both events, for both current master and the PR.

**Current master**:

|proxy1|proxy1<sup>_i_</sup> - proxy1<sup>_i-1_</sup>|proxy2|proxy2<sup>_i_</sup> - proxy2<sup>_i-1_</sup>|proxy2 - proxy1|
-----------------|----|-----------------|---|----
1562437848|-|1562437863|-|15
1562437938|90|1562437953|90|15
1562438028|90|1562438043|90|15
1562438118|90|1562438133|90|15
1562438208|90|1562438223|90|15

**PR branch**:

|proxy1|proxy1<sup>_i_</sup> - proxy1<sup>_i-1_</sup>|proxy2|proxy2<sup>_i_</sup> - proxy2<sup>_i-1_</sup>|proxy2 - proxy1|
-----------------|----|-----------------|---|----
1562439258|- |1562439333|- |75
1562439318|60|1562439393|60|75
1562439378|60|1562439453|60|75
1562439438|60|1562439513|60|75
1562439498|60|1562439573|60|75

An interesting result. The span of time between the executions in the events are now correct, but the delta between the events is not correct. The proxy2 event occurs 75 seconds after the proxy1 event, but the results _would_ be correct if the first proxy1 event never occurred. That is to say, if we consider proxy1<sup>_i_</sup> and proxy2<sup>_i-1_</sup> as matching events, then the results would be correct.

It seems likely that an additional small tweak would resolve this quirk.

**Comment by palourde** [comment]
Hi @roganartu,

Thanks again for the PR! We just had a discussion among ourselves and decided we should also fix the issue Eric identified in the previous comment before this change.

Do you think you will have the time to work on that in the next couple of days? And do you need help with that? Otherwise we can just take it from here too.

Thanks!

**Comment by roganartu** [comment]
I don't have time this week or probably next to look at it sorry.

**Comment by echlebek** [comment]
I looked at this a bit more today. I think that even though there is a slight discrepancy, it's still more correct behaviour than we have now. I also couldn't manage to resolve the discrepancy. So, I'm going to merge this PR. Thanks @roganartu!

**Pull request merged**
