### PR TITLE
Address first round of MEP papercuts

### PR DESCRIPTION
**Pull request by portertech**
## What is this change?

Addressing some of the Monitoring Event Pipeline workflow papercuts @calebhailey has identified (https://gist.github.com/calebhailey/9b63d62bd892d113a9d41326db23c67c)

1. Support both POST and PUT methods on the /api/core/v2/namespaces/:namespace/events/ endpoint and /api/core/v2/namespaces/:namespace/events/:entity/:check endpoints.

3. Reduce the number of required fields in the event; just namespace for now.

I also fixed an existing API router test, which was passing for the wrong reason.

Thoughts:

- Due to the nature of Events, you should always be able to use the POST verb
- The PUT verb is more for consistency with the other resource APIs

## Why is this change necessary?

It is difficult or impossible to demonstrate certain monitoring event pipeline workflows with Sensu Go.

## Does your change need a Changelog entry?

Yes.

## Do you need clarification on anything?

No.

## Were there any complications while making this change?

No.

## Have you reviewed and updated the documentation for this change? Is new documentation required?

No.

## How did you verify this change?

Updated and ran tests.

### CODE REVIEW

**Comment by portertech** [comment]
Going to refactor a bit and add resource id path value fallback.

**Comment by calebhailey** [comment]
:heart::heart::heart::heart::heart:

**Comment by cwjohnston** [comment]
This one is getting long in the tooth but I'd love to see these improvements shipped!

**Comment by calebhailey** [comment]
@portertech looks like we're planning on a 5.12 release for next week; can we include these improvements in that release? 🙏

**Comment by calebhailey** [comment]
Thanks Eric! 🙌

**Pull request merged**
