### PR TITLE
Add issue template for GitHub

### PR DESCRIPTION
**Pull request by palourde**
Signed-off-by: Simon Plourde <simon@sensu.io>

## What is this change?

It adds an issue template for GitHub.

## Why is this change necessary?

Closes https://github.com/sensu/sensu-go/issues/1135

## Does your change need a Changelog entry?

Added!

## Do you need clarification on anything?

Nope!

## Were there any complications while making this change?

Nope!

### CODE REVIEW

**Comment by palourde** [comment]
@grepory That's normal in markdown view, it does the same thing on sensu/sensu: https://github.com/sensu/sensu/blob/master/.github/ISSUE_TEMPLATE.md.

But they do appear in the raw view and they will also appear in the markdown editor when creating a new issue!

**Comment by grepory** [comment]
That is very bizarre and somewhat confusing. Can we just make them _underline_ instead?

**Comment by grepory** [comment]
Or is there some advantage to this that I'm missing?

**Comment by palourde** [comment]
I believe it's simply to reduce the noise if someone doesn't remove these instructions, but I don't really have an opinion on that.

Any thoughts @portertech @cwjohnston?

**Comment by grepory** [comment]
Does it go away if they submit without removing?

**Comment by grepory** [comment]
OK. I see how it works now. Sorry. Thanks :D

**Pull request merged**
