### PR TITLE
Increase embedded etcd heatbeat interval and election timeout defaults

### PR DESCRIPTION
**Pull request by portertech**
Increased the embedded etcd heatbeat interval and election timeout defaults.

Closes https://github.com/sensu/sensu-go/issues/4368

## What is this change?

Increased the embedded etc heatbeat interval and election timeout defaults, making etcd more latency tolerant for our use-case.

## Why is this change necessary?

Quality network an more importantly storage is harder to come by then expected. The etcd default values for the heatbeat interval and election timeout are too low, too sensitive to network and storage latency. etcd elections are expensive and destructive, increasing the default values helps avoid them while still not being too high that leader failover takes too long.

## Does your change need a Changelog entry?

Yes.

## Do you need clarification on anything?

No.

## Were there any complications while making this change?

No.

## Have you reviewed and updated the documentation for this change? Is new documentation required?

No.

## How did you verify this change?

Local build.

## Is this change a patch?

No.

### CODE REVIEW

**Review by echlebek — APPROVED** [review]
yolo

**Review by echlebek — CHANGES_REQUESTED** [review]
@portertech this seems to be causing integration test failures. I think we'll need to spend a bit more time on this PR.

**Comment by ccressent** [comment]
For some reason I don't quite understand, this change makes it so the entity doesn't have enough time to deregister [in that part of the test](https://github.com/sensu/sensu-go/blob/71cb3f4d70d8b2b7b02aa3e616f43626a7bb3e4a/backend/keepalived/integration_test.go#L133-L149).

If the timer expires before the entity has been deregistered, the test fails.
If the timer lasts for long enough to have the following line logged, the test passes:
```
time="2021-09-30T12:18:24-07:00" level=info msg="entity deregistered" component=keepalived entity=entity1
```

Bumping [this test's keepalive timeout](https://github.com/sensu/sensu-go/blob/71cb3f4d70d8b2b7b02aa3e616f43626a7bb3e4a/backend/keepalived/integration_test.go#L72) from 5 to 10 seems to do the trick on my machine.

As it stands I'm not committing this change to the test because I don't quite understand how changing the etcd heartbeat form 100ms to 500ms would have caused this test to fail in the first place... My main concern is that there _might_ be other unintended consequences we are just not grasping yet?

**Comment by portertech** [comment]
Until we understand the impact of changing this default value, we aren't comfortable merging this pull-request. Many users already use these values (of greater values), it's not clear what side-effects they are experiencing (likely unaware). Changing the milestone.

**Review by c-kruse — COMMENTED** [review]
@portertech with the keepalive integration test failure explained by etcd's minimum lease ttl == 1.5x election timeout, do we feel good about moving forward with your idea to compromise on lower defaults that still allow for our 5 second min keepalive ttl - 330ms heartbeat with a 3300ms election timeout?

It looks like those values are consistently passing integration tests on my machine. It looks like for any value for heartbeat > 333ms, the keepalive integration test will fail - which makes sense if you look at etcd's minTTL implementation `time.Duration((3*cfg.ElectionTicks)/2) * heartbeat`

**Comment by echlebek** [comment]
This PR has aged considerably. I'm closing it, we can revisit it at a later date if need be.

**Pull request closed without merging**
