### PR TITLE
Enable linting for our Go modules

### PR DESCRIPTION
**Pull request by amdprophet**
Signed-off-by: Justin Kolberg <amd.prophet@gmail.com>

## What is this change?

Piggybacking off of #3849 to add support for our Go modules.

## Why is this change necessary?

See #3689

## Does your change need a Changelog entry?

Nope!

## Do you need clarification on anything?

Nope!

## Were there any complications while making this change?

I couldn't find a way to set the version of golangci-lint once and reuse it for each GitHub Actions job.

## Have you reviewed and updated the documentation for this change? Is new documentation required?

Nope!

## How did you verify this change?

Ran the linter locally.

## Is this change a patch?

No.

### CODE REVIEW

**Comment by amdprophet** [comment]
I believe the error in the integration test was never exposed before as the test name was incorrect. I'll look into what's going on with it tomorrow.

**Comment by echlebek** [comment]
Oops, looks like some tests are failing.

**Comment by amdprophet** [comment]
@palourde do you have any opinions on what we should do with the failing test?

**Comment by echlebek** [comment]
@amdprophet was that question intended for me?

**Pull request merged**
