### PR TITLE
Ringv2: update deps

### PR DESCRIPTION
**Pull request by vooon**
## What is this change?

That PR removes dependency on old cron package, the only place not yet updated to cron/v3.
And fixes `UnPath()` (my eyes was being captured by strange indexes, so i wrote test unit to prove me wrong, but it wasn't).

## Why is this change necessary?

- Removes outdated dependency
- Fixes bug in a function without any calls...

## Does your change need a Changelog entry?

Probbaly no, because there is no real changes.

## Do you need clarification on anything?
No.

## Were there any complications while making this change?
No.

## Have you reviewed and updated the documentation for this change? Is new documentation required?
No.

## How did you verify this change?
Compilled, ran tests.

## Is this change a patch?
Well yes, function fix is a patch, but i do not see any calls from whole codebase to it.

### CODE REVIEW

**Comment by vooon** [comment]
Appveyor failure looks unrelated.

**Review by jamesdphillips — CHANGES_REQUESTED** [review]
This looks great, thanks for the submission!

If you don't mind, would you revert the additional test? I think it would be unforntunate to add an additional dependency just to test a function that is currently unused. (Or, otherwise update the test omitting the random elements, maybe we use fuzzing in the future if we want to test a wider range of possible inputs.)

**Comment by vooon** [comment]
@jamesdphillips randstr removed.

**Review by jamesdphillips — APPROVED** [review]
Beaut

**Review by fguimond — APPROVED** [review]
lgtm

**Pull request merged**
