### PR TITLE
add restclient apikey support

### PR DESCRIPTION
**Pull request by fgouteroux**
## What is this change?

This commit adds the support of apikey lifecycle for the restclient.

## Why is this change necessary?

This change is necessary in order to align the cli with the restclient and also as some others modules are using this module like https://github.com/jtopjian/terraform-provider-sensu.

## How did you verify this change?

This change has been tested with the forked project [terraform-provider-sensu](https://github.com/fgouteroux/terraform-provider-sensu/commit/0fd372c57dbd3a132839e2d1a16151d48ca7ecc3)

### CODE REVIEW

**Review by echlebek — COMMENTED** [review]
We need automated tests for this work. The package overall is poorly tested, but that will only get worse if we don't add tests for new code. Even if the code works as-is, we'll be unprotected from regressions.

Let's add some tests that are similar to those written for authentication, so that we can move forward with confidence.

**Comment by fgouteroux** [comment]
> We need automated tests for this work. The package overall is poorly tested, but that will only get worse if we don't add tests for new code. Even if the code works as-is, we'll be unprotected from regressions.
> 
> Let's add some tests that are similar to those written for authentication, so that we can move forward with confidence.

Yes, I understand. I added some tests, is that enough ?

**Review by echlebek — APPROVED** [review]

**Comment by echlebek** [comment]
Thank you for the great work @fgouteroux!

**Comment by fgouteroux** [comment]
> Thank you for the great work @fgouteroux!

Thanks for the review @echlebek

**Pull request merged**
