### PR TITLE
Prevent agent from immediately exiting in certain scenarios

### PR DESCRIPTION
**Pull request by palourde**
Signed-off-by: Simon Plourde <simon@sensu.io>

## What is this change?

It increases the agent waitgroup counter for all possible paths, so even if certain components are disabled, the agent does not immediately exit. The system info collector is not responsible for decrement it once it returns.

## Why is this change necessary?

Closes https://github.com/sensu/sensu-go/issues/3819

## Does your change need a Changelog entry?

Added

## Do you need clarification on anything?

Nope

## Were there any complications while making this change?

Nope

## Have you reviewed and updated the documentation for this change? Is new documentation required?

Nope

## How did you verify this change?
Manually verified; I'm not sure how we can easily test it via an integration or even e2e test.

## Is this change a patch?

Yep

### CODE REVIEW

**Comment by palourde** [comment]
@echlebek Yeah, I can try to see if refactoring the agent so it behaves a bit more like the backend is possible without doing major changes.

**Comment by echlebek** [comment]
I ran into this issue when testing:
```
[eric@cube sensu-go]$ sensu-agent start --disable-sockets --disable-assets --disable-api --statsd-disable --cache-dir ./acache
{"component":"agent","error":"lasr: Q is closed","level":"error","msg":"error receiving message from queue","time":"2020-06-03T10:54:11-07:00"}
{"component":"agent","error":"lasr: Q is closed","level":"error","msg":"error receiving message from queue","time":"2020-06-03T10:54:11-07:00"}
{"component":"agent","error":"lasr: Q is closed","level":"error","msg":"error receiving message from queue","time":"2020-06-03T10:54:11-07:00"}
{"component":"agent","error":"lasr: Q is closed","level":"error","msg":"error receiving message from queue","time":"2020-06-03T10:54:11-07:00"}
{"component":"agent","error":"lasr: Q is closed","level":"error","msg":"error receiving message from queue","time":"2020-06-03T10:54:11-07:00"}

```

**Comment by palourde** [comment]
@echlebek Can you try again with the latest commits? It should work now

**Comment by echlebek** [comment]
Successfully tested!

**Comment by palourde** [comment]
Successfully tested on sensu-staging 🎉

**Pull request merged**
