### PR TITLE
Prometheus check output format transformer

### LINKED ISSUE #2147: RFE: Support Prometheus text metric format as ingestable metrics format.
Add support for the prometheus text metric format.

### Reference:
https://prometheus.io/docs/instrumenting/exposition_formats/#text-based-format

### Important Note: 
CNCF has a sandbox project called OpenMetrics to create a standardize json metric format that is an out growth of Prometheus.  It's still early stages, but it's something to watch. Once they release a format standard out of OpenMetrics it would be great to be able to flip the switch in sensu and be able to support it as a metric format.

### PR DESCRIPTION
**Pull request by portertech**
## What is this change?

Add support for transforming Prometheus Exposition Text Format check output to Sensu Go event metrics.

Closes #2147

## Why is this change necessary?

The [Prometheus Exposition Text Format](https://prometheus.io/docs/instrumenting/exposition_formats/#text-based-format) has become common and can be considered an "industry standard format" for metric output. The Prometheus ecosystem provides a number of metric exporters, services that collect, compute, and expose metrics in the Prometheus Exposition Text Format. Adding support for this format to Sensu Go Agent metric check output metric extraction makes sense, checks can scrape Prometheus exporters or produce their own metrics in the Exposition Text Format.

## Does your change need a Changelog entry?

Yes. Updated in this PR.

## Do you need clarification on anything?

Testing the Prometheus transformer requires metric timestamps with second resolution. Will these tests be "fragile"? They were fine for PR CI runs. Is there a better way?

## Were there any complications while making this change?

Nope.

## Have you reviewed and updated the documentation for this change? Is new documentation required?

|output_metric_format    |      |
-------------|------
description  | Metric format generated by the check command. Sensu supports the following metric formats: <br>`nagios_perfdata` ([Nagios Performance Data][46]) <br>`prometheus_text` ([Prometheus Exposition Text][TODO]) <br>`graphite_plaintext` ([Graphite Plaintext Protocol][47]) <br>`influxdb_line` ([InfluxDB Line Protocol][48]) <br>`opentsdb_line` ([OpenTSDB Data Specification][49])<br><br>When a check includes an `output_metric_format`, Sensu will extract the metrics from the check output and add them to the event data in [Sensu metric format][50]. Read [Collect metrics with Sensu checks][23].
required     | false
type         | String
example      | {{< code shell >}}"output_metric_format": "graphite_plaintext"{{< /code >}}

## How did you verify this change?

Created a check that scraped a Prometheus exporter, `curl -s http://127.0.0.1:9091/metrics`, using `output_metric_format: prometheus_text`.

## Is this change a patch?

No.

### CODE REVIEW

**Comment by calebhailey** [comment]
Closes #2147

**Comment by nikkictl** [comment]
@hillaryfraley see docs updates above for https://docs.sensu.io/sensu-go/latest/guides/extract-metrics-with-checks/#supported-output-metric-formats

**Comment by nikkictl** [comment]
Filed https://github.com/sensu/sensu-docs/issues/2650.

**Comment by calebhailey** [comment]
Edited the PR description to link it to the original issue.

**Comment by nikkictl** [comment]
Performed some rebases so I could apply the changes in enterprise for testing: https://github.com/sensu/sensu-enterprise-go/pull/1195

**Comment by portertech** [comment]
antonio-banderas

**Pull request merged**
