### PR TITLE
[WIP] AIX support

### LINKED ISSUE #2944: Sensu Agent AIX Support ?
Hello Sensu Team,
Is Sensu Agent Go planned to support AIX systems?
It was probably asked bazillion times but I can't find the information anywhere.

### PR DESCRIPTION
**Pull request by amdprophet**
## What is this change?

Adds changes required to build Sensu Agent on `aix/ppc64`. We'll have to use our fork of the following repositories:
* https://github.com/fsnotify/fsnotify
* https://github.com/spf13/afero

until the PRs listed in https://github.com/sensu/sensu-go/issues/2944#issuecomment-557679449 have been merged.

## Why is this change necessary?

Fixes #2944.

AIX is one of the platforms we want to support.

## Does your change need a Changelog entry?

Yes.

## Have you reviewed and updated the documentation for this change? Is new documentation required?

No new documentation with this PR as it's not adding any new builds.

## How did you verify this change?

`GOOS=aix GOOS=ppc64 go build ./cmd/sensu-agent` successfully produces a binary.

## Is this change a patch?

No.

### CODE REVIEW

**Comment by echlebek** [comment]
It seems possible that the fsnotify changes may have broken some things on linux/amd64

**Comment by amdprophet** [comment]
Looking into it now.

**Comment by amdprophet** [comment]
It doesn't seem to be fsnotify. I'll go through the list of modules that were updated in this PR and try to figure it out in the morning.

**Comment by echlebek** [comment]
Can we close this PR and reopen when AIX support is working?

**Pull request closed without merging**
